### ISSUE TITLE
Enforce rootless containers in helm test workflow

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/e2e-testing#12]
# Description

Our Release Guideline [4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) requires every Tractus-X FOSS app to run rootless.
We should enforce this guideline by enforcing it in our helm test / kind workflow, so that we do not have to check it manually each Quality Gate. One option could be to install [kyverno](https://github.com/kyverno/kyverno/)  and create a nonroot policy that is applied to the kind cluster.

**Comment by almadigabor** [comment]
An [example](https://kyverno.io/policies/pod-security/restricted/require-run-as-nonroot/require-run-as-nonroot/) for applying a cluster wide kyverno policy to enforce `runAsNonRoot: true`.

**Comment by Siegfriedk** [comment]
We should definitly do that sooner than later. i'm not aware of any one needing root and i informed a team just a month ago that they were running as root and they were just not awaer of it.

**Comment by almadigabor** [comment]
I'll look into this by installing kyverno in the workflow and adding a `ClusterPolicy` to enforce `runAsNonRoot: true` in the pod specifications.
