### ISSUE TITLE
Enable Helm lint for PR branches

### ISSUE THREAD

**Issue by fty4** [eclipse-tractusx/e2e-testing#15]
Would it not be better if the ct lint wf runs also on other branches or at least on PRs?

https://github.com/eclipse-tractusx/e2e-testing/blob/5c50364406bb51e40b330910864d628bbcfc9fc6/.github/workflows/helm-lint.yaml#L22-L27

Currently the wf is only triggered on `main` branch or manually.

**Comment by fty4** [comment]
Only relevant if **NOT** checked for diffs:

```
Linting charts...
--------------------------------------------------------------------------------------------------
No chart changes detected.
--------------------------------------------------------------------------------------------------
All charts linted successfully
```

**Comment by almadigabor** [comment]
Yes, definitely should be running on PRs. In our example workflow the trigger is on PRs when charts dir changes.

https://github.com/catenax-ng/k8s-helm-example/blob/main/.github/workflows/helm-lint-and-test.yaml#L3-L6

**Comment by fty4** [comment]
Issue was wrong - the `branches: main` declare that the PR base needs to be main which is fine.
