### ISSUE TITLE
Use regular tx-c Helm chart instead of legacy 

### ISSUE THREAD

**Issue by fty4** [eclipse-tractusx/e2e-testing#27]
Currently we are using the [legacy chart](https://github.com/eclipse-tractusx/tractusx-edc/tree/0.5.0-rc1/charts/tractusx-connector-legacy) of tractusx-connector:

https://github.com/eclipse-tractusx/e2e-testing/blob/c5a5d0699a325c5922d48abf2a5c97cc0e107338/charts/umbrella/Chart.yaml#L41-L50

But instead of installing the `0.5.0` image the version will be set to `0.4.1`.

This should be changed later.

Also see comment in: 
https://github.com/eclipse-tractusx/e2e-testing/blob/c5a5d0699a325c5922d48abf2a5c97cc0e107338/charts/umbrella/values.yaml#L22-L24

linked to #22

**Comment by almadigabor** [comment]
This is outdated now, and will create new issue for adding components and values (like EDC). Closing for now.
