### ISSUE TITLE
Same trigger for helm test workflow as in helm lint

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/e2e-testing#29]
I would suggest using the same trigger for dispatching [helm test workflow](https://github.com/eclipse-tractusx/e2e-testing/blob/719eb1aaf6a8a04b36ae6c89e0f26c62c3cfca4e/.github/workflows/helm-test.yaml#L22) as in [helm lint](https://github.com/eclipse-tractusx/e2e-testing/blob/main/.github/workflows/helm-lint.yaml#L22) because it is sufficient to make the tests when the chart is changed.

**Comment by fty4** [comment]
I totally agree with your suggestion - maybe if the same trigger is used both jobs can be merged into one workflow (e.g. named Helm).

**Comment by almadigabor** [comment]
Agree, can be merged into a single wf

**Comment by almadigabor** [comment]
This has been done with PR https://github.com/eclipse-tractusx/e2e-testing/pull/42
